name: Build
env:
  CACHE_NAME: purescript-unlift
  TRUSTED_PUBLIC_KEYS: "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= purescript-unlift.cachix.org-1:1gPjVFpu4QjaAT3tRurCioX+BC23V7mjvFwpP5bV0Ec="
  SUBSTITUTERS: "https://cache.nixos.org/ https://purescript-unlift.cachix.org"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          install_url: https://releases.nixos.org/nix/nix-2.5.1/install
          extra_nix_config: |
            trusted-public-keys = ${{ env.TRUSTED_PUBLIC_KEYS }}
            substituters = ${{ env.SUBSTITUTERS }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: ${{ env.CACHE_NAME }}
          authToken: "${{ secrets.TWEAG_CACHIX_AUTH_TOKEN }}"
      - run: nix build
